//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WantToLearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_tbl
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Lecturer { get; set; }
        public string PDFs_Links { get; set; }
        public string Level { get; set; }
    
        public virtual Lecturer_tbl Lecturer_tbl { get; set; }
    }
}
