//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WantToLearn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MostaLearningEntities : DbContext
    {
        public MostaLearningEntities()
            : base("name=MostaLearningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_tbl> Admin_tbl { get; set; }
        public virtual DbSet<Course_tbl> Course_tbl { get; set; }
        public virtual DbSet<Lecturer_tbl> Lecturer_tbl { get; set; }
        public virtual DbSet<Student_tbl> Student_tbl { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
